version: '3.7'

services:
  db:
    image: postgres:13.4
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dbinit:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepassword
      POSTGRES_DB: sampledb
    networks:
      - backend
  backend:
    build: backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - backend
    restart: "on-failure"
    environment:
      SMPL_DBCONNECT: 'sampleuser:samplepassword@db/sampledb?sslmode=disable'
  frontend:
    build: frontend
    ports:
      - '8000:80'
    depends_on:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  db_data: null
